/* ----
  DO THIS SCRIPT WHEN PAGE LOADS
  SHOLLD ADD THIS FILE TO YOUR CHILD THEME JS FOLDER
  ----- */
jQuery(document).ready(function() {

// 3 . ADD MACARON TO BASKET ON CLICK -- WAS ADDED TO THEME WOOCOMMERCE JS FOLDER


});
